### ISSUE TITLE
PRにreview aiとコメントしたらレビューするGitHub Actionsのワークフローを追加したい

### ISSUE THREAD

**Issue by tsuno08** [tsuno08/aici#1]
# PRレビューAIワークフロー設計書

## 概要
Pull Requestに「review ai」とコメントされた場合、AIによるコードレビューを自動実行し、日本語でコメントを投稿するGitHub Actionsワークフロー

## ワークフロー詳細

```mermaid
graph TD
    A[PRに review ai コメント] --> B[ワークフロー起動]
    B --> C[PRの差分取得]
    C --> D[AIによるコードレビュー]
    D --> E[日本語でレビューコメント生成]
    E --> F[PRにコメント投稿]
```

### トリガー条件
```yaml
on:
  issue_comment:
    types: [created]
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, 'review ai')
```

### 実行環境
- ランナー: `ubuntu-latest`
- Node.jsバージョン: `22.x` (既存環境と統一)

### 主要ステップ
1. **PR差分取得**:
   ```yaml
   - uses: actions/checkout@v4
     with:
       ref: ${{ github.event.pull_request.head.ref }}
   - run: git diff origin/main > diff.txt
   ```

2. **AIコードレビュー**:
   ```yaml
   - name: Analyze code with AI
     env:
       DIFF_CONTENT: ${{ steps.get_diff.outputs.content }}
       OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
     run: |
       review=$(curl -s https://openrouter.ai/api/v1/chat/completions \
         -H "Authorization: Bearer $OPENROUTER_API_KEY" \
         -H "Content-Type: application/json" \
         -d '{
           "model": "deepseek/deepseek-chat-v3-0324:free",
           "messages": [
             {
               "role": "system",
               "content": "以下のコード差分を日本語で技術的にレビューしてください。改善点、潜在的なバグ、ベストプラクティスからの逸脱などを指摘してください。"
             },
             {
               "role": "user",
               "content": "$DIFF_CONTENT"
             }
           ]
         }' | jq -r '.choices[0].message.content')
       echo "$review" > review_comment.txt
   ```

3. **PRコメント投稿**:
   ```yaml
   - name: Post review comment
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: |
       gh pr comment ${{ github.event.pull_request.number }} \
         --body "$(cat review_comment.txt)"
   ```

## 必要なSecrets
- `OPENROUTER_API_KEY`: OpenRouterのAPIキー
- `GITHUB_TOKEN`: GitHubのデフォルトトークン

## 既存システムとの統合
- 既存のOpenRouter/Gemini設定を流用
- 日本語出力フォーマットを統一
